# Generated by Django 5.2.12 on 2026-04-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_autor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
