# Generated by Django 5.2.13 on 2026-04-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_editora_cidade_editora_email'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.image'),
        ),
    ]
