# Generated by Django 5.2.13 on 2026-04-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
    ]
